"""Initial migration

Revision ID: 2bd135933975
Revises: None
Create Date: 2026-05-29 10:47:16.537141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd135933975'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('late_threshold', sa.String(length=10), nullable=False),
    sa.Column('late_penalty', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portal_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('opening_to_give', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('opening_to_take', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_groups_name'), 'portal_groups', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('virtual_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('attendance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_km', sa.Integer(), nullable=False),
    sa.Column('end_km', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_km_image_url', sa.String(length=500), nullable=True),
    sa.Column('end_km_image_url', sa.String(length=500), nullable=True),
    sa.Column('start_latitude', sa.Float(), nullable=True),
    sa.Column('start_longitude', sa.Float(), nullable=True),
    sa.Column('end_latitude', sa.Float(), nullable=True),
    sa.Column('end_longitude', sa.Float(), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('penalty_amount', sa.Float(), nullable=False),
    sa.Column('is_penalty_approved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('portal_name', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_no', sa.String(length=100), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('opening_to_give', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('opening_to_take', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['portal_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portals_portal_name'), 'portals', ['portal_name'], unique=False)
    op.create_table('retailers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('retailer_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('assigned_staff_id', sa.Uuid(), nullable=True),
    sa.Column('ledger_token', sa.String(length=50), nullable=False),
    sa.Column('opening_to_give', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('opening_to_take', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailers_ledger_token'), 'retailers', ['ledger_token'], unique=True)
    op.create_index(op.f('ix_retailers_phone'), 'retailers', ['phone'], unique=True)
    op.create_index(op.f('ix_retailers_retailer_name'), 'retailers', ['retailer_name'], unique=False)
    op.create_table('bank_deposits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('deposit_type', sa.String(length=20), nullable=False),
    sa.Column('portal_id', sa.Uuid(), nullable=True),
    sa.Column('retailer_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_staff_id', sa.Uuid(), nullable=True),
    sa.Column('to_office', sa.Boolean(), nullable=False),
    sa.Column('payment_mode', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_date', sa.Date(), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('balance_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_staff_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_no')
    )
    op.create_table('stores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('retailer_id', sa.Uuid(), nullable=False),
    sa.Column('store_name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_store_name'), 'stores', ['store_name'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('retailer_id', sa.Uuid(), nullable=True),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('from_staff_id', sa.Uuid(), nullable=True),
    sa.Column('from_office', sa.Boolean(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('portal_id', sa.Uuid(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('collection_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('balance_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_staff_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('denominations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=True),
    sa.Column('deposit_id', sa.Uuid(), nullable=True),
    sa.Column('note_500', sa.Integer(), nullable=False),
    sa.Column('note_200', sa.Integer(), nullable=False),
    sa.Column('note_100', sa.Integer(), nullable=False),
    sa.Column('note_50', sa.Integer(), nullable=False),
    sa.Column('note_20', sa.Integer(), nullable=False),
    sa.Column('note_10', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('online_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deposit_id'], ['bank_deposits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledgers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('retailer_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('collection_id', sa.Uuid(), nullable=True),
    sa.Column('deposit_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deposit_id'], ['bank_deposits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledgers')
    op.drop_table('denominations')
    op.drop_table('collections')
    op.drop_index(op.f('ix_stores_store_name'), table_name='stores')
    op.drop_table('stores')
    op.drop_table('bank_deposits')
    op.drop_index(op.f('ix_retailers_retailer_name'), table_name='retailers')
    op.drop_index(op.f('ix_retailers_phone'), table_name='retailers')
    op.drop_index(op.f('ix_retailers_ledger_token'), table_name='retailers')
    op.drop_table('retailers')
    op.drop_index(op.f('ix_portals_portal_name'), table_name='portals')
    op.drop_table('portals')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_portal_groups_name'), table_name='portal_groups')
    op.drop_table('portal_groups')
    op.drop_table('business_settings')
    # ### end Alembic commands ###
