"""add_staff_wise_late_policy_settings

Revision ID: 3408cd071d9a
Revises: 2bd135933975
Create Date: 2026-06-08 17:25:47.963921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3408cd071d9a'
down_revision: Union[str, None] = '2bd135933975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_settings', 'auto_checkout_time',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'20:00'::character varying"))
    op.add_column('users', sa.Column('late_threshold', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('late_penalty', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('auto_checkout_time', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auto_checkout_time')
    op.drop_column('users', 'late_penalty')
    op.drop_column('users', 'late_threshold')
    op.alter_column('business_settings', 'auto_checkout_time',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'20:00'::character varying"))
    # ### end Alembic commands ###
